/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppSideRouteImport } from './routes/app.side'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppLeeRouteImport } from './routes/app.lee'
import { Route as AppKpisRouteImport } from './routes/app.kpis'
import { Route as AppEvaluacionCompetenciasRouteImport } from './routes/app.evaluacion-competencias'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCrecimientoRouteImport } from './routes/app.crecimiento'
import { Route as AppConfiguracionRouteImport } from './routes/app.configuracion'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAdminSimpleRouteImport } from './routes/app.admin-simple'
import { Route as AppManualFuncionesIndexRouteImport } from './routes/app.manual-funciones.index'
import { Route as AppCoachingIndexRouteImport } from './routes/app.coaching.index'
import { Route as AppSideHistorialRouteImport } from './routes/app.side_.historial'
import { Route as AppManualFuncionesClienteIdRouteImport } from './routes/app.manual-funciones.$clienteId'
import { Route as AppCoachingResultadosRouteImport } from './routes/app.coaching.resultados'
import { Route as AppCoachingMetodologiaRouteImport } from './routes/app.coaching.metodologia'
import { Route as AppClientesClienteIdRouteImport } from './routes/app.clientes.$clienteId'
import { Route as AppClientesClienteIdSideRouteImport } from './routes/app.clientes.$clienteId.side'
import { Route as AppClientesClienteIdResumenRouteImport } from './routes/app.clientes.$clienteId.resumen'
import { Route as AppClientesClienteIdPlanRouteImport } from './routes/app.clientes.$clienteId.plan'
import { Route as AppClientesClienteIdOnboardingRouteImport } from './routes/app.clientes.$clienteId.onboarding'
import { Route as AppClientesClienteIdLeeRouteImport } from './routes/app.clientes.$clienteId.lee'
import { Route as AppClientesClienteIdEmpresaRouteImport } from './routes/app.clientes.$clienteId.empresa'
import { Route as AppClientesClienteIdCotizacionesRouteImport } from './routes/app.clientes.$clienteId.cotizaciones'
import { Route as AppClientesClienteIdContactosRouteImport } from './routes/app.clientes.$clienteId.contactos'
import { Route as AppClientesClienteIdCoachingRouteImport } from './routes/app.clientes.$clienteId.coaching'
import { Route as AppClientesClienteIdAnalisisIaRouteImport } from './routes/app.clientes.$clienteId.analisis-ia'
import { Route as AppClientesClienteIdActividadesRouteImport } from './routes/app.clientes.$clienteId.actividades'
import { Route as AppClientesClienteIdLeeCapituloRouteImport } from './routes/app.clientes.$clienteId.lee.$capitulo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSideRoute = AppSideRouteImport.update({
  id: '/side',
  path: '/side',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppLeeRoute = AppLeeRouteImport.update({
  id: '/lee',
  path: '/lee',
  getParentRoute: () => AppRoute,
} as any)
const AppKpisRoute = AppKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluacionCompetenciasRoute =
  AppEvaluacionCompetenciasRouteImport.update({
    id: '/evaluacion-competencias',
    path: '/evaluacion-competencias',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrecimientoRoute = AppCrecimientoRouteImport.update({
  id: '/crecimiento',
  path: '/crecimiento',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSimpleRoute = AppAdminSimpleRouteImport.update({
  id: '/admin-simple',
  path: '/admin-simple',
  getParentRoute: () => AppRoute,
} as any)
const AppManualFuncionesIndexRoute = AppManualFuncionesIndexRouteImport.update({
  id: '/manual-funciones/',
  path: '/manual-funciones/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingIndexRoute = AppCoachingIndexRouteImport.update({
  id: '/coaching/',
  path: '/coaching/',
  getParentRoute: () => AppRoute,
} as any)
const AppSideHistorialRoute = AppSideHistorialRouteImport.update({
  id: '/side_/historial',
  path: '/side/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppManualFuncionesClienteIdRoute =
  AppManualFuncionesClienteIdRouteImport.update({
    id: '/manual-funciones/$clienteId',
    path: '/manual-funciones/$clienteId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoachingResultadosRoute = AppCoachingResultadosRouteImport.update({
  id: '/coaching/resultados',
  path: '/coaching/resultados',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingMetodologiaRoute = AppCoachingMetodologiaRouteImport.update({
  id: '/coaching/metodologia',
  path: '/coaching/metodologia',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesClienteIdSideRoute =
  AppClientesClienteIdSideRouteImport.update({
    id: '/side',
    path: '/side',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdResumenRoute =
  AppClientesClienteIdResumenRouteImport.update({
    id: '/resumen',
    path: '/resumen',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdPlanRoute =
  AppClientesClienteIdPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdOnboardingRoute =
  AppClientesClienteIdOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdLeeRoute = AppClientesClienteIdLeeRouteImport.update({
  id: '/lee',
  path: '/lee',
  getParentRoute: () => AppClientesClienteIdRoute,
} as any)
const AppClientesClienteIdEmpresaRoute =
  AppClientesClienteIdEmpresaRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdCotizacionesRoute =
  AppClientesClienteIdCotizacionesRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdContactosRoute =
  AppClientesClienteIdContactosRouteImport.update({
    id: '/contactos',
    path: '/contactos',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdCoachingRoute =
  AppClientesClienteIdCoachingRouteImport.update({
    id: '/coaching',
    path: '/coaching',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdAnalisisIaRoute =
  AppClientesClienteIdAnalisisIaRouteImport.update({
    id: '/analisis-ia',
    path: '/analisis-ia',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdActividadesRoute =
  AppClientesClienteIdActividadesRouteImport.update({
    id: '/actividades',
    path: '/actividades',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdLeeCapituloRoute =
  AppClientesClienteIdLeeCapituloRouteImport.update({
    id: '/$capitulo',
    path: '/$capitulo',
    getParentRoute: () => AppClientesClienteIdLeeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin-simple': typeof AppAdminSimpleRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/crecimiento': typeof AppCrecimientoRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/evaluacion-competencias': typeof AppEvaluacionCompetenciasRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRouteWithChildren
  '/app/coaching/metodologia': typeof AppCoachingMetodologiaRoute
  '/app/coaching/resultados': typeof AppCoachingResultadosRoute
  '/app/manual-funciones/$clienteId': typeof AppManualFuncionesClienteIdRoute
  '/app/side/historial': typeof AppSideHistorialRoute
  '/app/coaching/': typeof AppCoachingIndexRoute
  '/app/manual-funciones/': typeof AppManualFuncionesIndexRoute
  '/app/clientes/$clienteId/actividades': typeof AppClientesClienteIdActividadesRoute
  '/app/clientes/$clienteId/analisis-ia': typeof AppClientesClienteIdAnalisisIaRoute
  '/app/clientes/$clienteId/coaching': typeof AppClientesClienteIdCoachingRoute
  '/app/clientes/$clienteId/contactos': typeof AppClientesClienteIdContactosRoute
  '/app/clientes/$clienteId/cotizaciones': typeof AppClientesClienteIdCotizacionesRoute
  '/app/clientes/$clienteId/empresa': typeof AppClientesClienteIdEmpresaRoute
  '/app/clientes/$clienteId/lee': typeof AppClientesClienteIdLeeRouteWithChildren
  '/app/clientes/$clienteId/onboarding': typeof AppClientesClienteIdOnboardingRoute
  '/app/clientes/$clienteId/plan': typeof AppClientesClienteIdPlanRoute
  '/app/clientes/$clienteId/resumen': typeof AppClientesClienteIdResumenRoute
  '/app/clientes/$clienteId/side': typeof AppClientesClienteIdSideRoute
  '/app/clientes/$clienteId/lee/$capitulo': typeof AppClientesClienteIdLeeCapituloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin-simple': typeof AppAdminSimpleRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/crecimiento': typeof AppCrecimientoRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/evaluacion-competencias': typeof AppEvaluacionCompetenciasRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRouteWithChildren
  '/app/coaching/metodologia': typeof AppCoachingMetodologiaRoute
  '/app/coaching/resultados': typeof AppCoachingResultadosRoute
  '/app/manual-funciones/$clienteId': typeof AppManualFuncionesClienteIdRoute
  '/app/side/historial': typeof AppSideHistorialRoute
  '/app/coaching': typeof AppCoachingIndexRoute
  '/app/manual-funciones': typeof AppManualFuncionesIndexRoute
  '/app/clientes/$clienteId/actividades': typeof AppClientesClienteIdActividadesRoute
  '/app/clientes/$clienteId/analisis-ia': typeof AppClientesClienteIdAnalisisIaRoute
  '/app/clientes/$clienteId/coaching': typeof AppClientesClienteIdCoachingRoute
  '/app/clientes/$clienteId/contactos': typeof AppClientesClienteIdContactosRoute
  '/app/clientes/$clienteId/cotizaciones': typeof AppClientesClienteIdCotizacionesRoute
  '/app/clientes/$clienteId/empresa': typeof AppClientesClienteIdEmpresaRoute
  '/app/clientes/$clienteId/lee': typeof AppClientesClienteIdLeeRouteWithChildren
  '/app/clientes/$clienteId/onboarding': typeof AppClientesClienteIdOnboardingRoute
  '/app/clientes/$clienteId/plan': typeof AppClientesClienteIdPlanRoute
  '/app/clientes/$clienteId/resumen': typeof AppClientesClienteIdResumenRoute
  '/app/clientes/$clienteId/side': typeof AppClientesClienteIdSideRoute
  '/app/clientes/$clienteId/lee/$capitulo': typeof AppClientesClienteIdLeeCapituloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin-simple': typeof AppAdminSimpleRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/crecimiento': typeof AppCrecimientoRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/evaluacion-competencias': typeof AppEvaluacionCompetenciasRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRouteWithChildren
  '/app/coaching/metodologia': typeof AppCoachingMetodologiaRoute
  '/app/coaching/resultados': typeof AppCoachingResultadosRoute
  '/app/manual-funciones/$clienteId': typeof AppManualFuncionesClienteIdRoute
  '/app/side_/historial': typeof AppSideHistorialRoute
  '/app/coaching/': typeof AppCoachingIndexRoute
  '/app/manual-funciones/': typeof AppManualFuncionesIndexRoute
  '/app/clientes/$clienteId/actividades': typeof AppClientesClienteIdActividadesRoute
  '/app/clientes/$clienteId/analisis-ia': typeof AppClientesClienteIdAnalisisIaRoute
  '/app/clientes/$clienteId/coaching': typeof AppClientesClienteIdCoachingRoute
  '/app/clientes/$clienteId/contactos': typeof AppClientesClienteIdContactosRoute
  '/app/clientes/$clienteId/cotizaciones': typeof AppClientesClienteIdCotizacionesRoute
  '/app/clientes/$clienteId/empresa': typeof AppClientesClienteIdEmpresaRoute
  '/app/clientes/$clienteId/lee': typeof AppClientesClienteIdLeeRouteWithChildren
  '/app/clientes/$clienteId/onboarding': typeof AppClientesClienteIdOnboardingRoute
  '/app/clientes/$clienteId/plan': typeof AppClientesClienteIdPlanRoute
  '/app/clientes/$clienteId/resumen': typeof AppClientesClienteIdResumenRoute
  '/app/clientes/$clienteId/side': typeof AppClientesClienteIdSideRoute
  '/app/clientes/$clienteId/lee/$capitulo': typeof AppClientesClienteIdLeeCapituloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/admin-simple'
    | '/app/clientes'
    | '/app/configuracion'
    | '/app/crecimiento'
    | '/app/dashboard'
    | '/app/evaluacion-competencias'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/share/$token'
    | '/app/clientes/$clienteId'
    | '/app/coaching/metodologia'
    | '/app/coaching/resultados'
    | '/app/manual-funciones/$clienteId'
    | '/app/side/historial'
    | '/app/coaching/'
    | '/app/manual-funciones/'
    | '/app/clientes/$clienteId/actividades'
    | '/app/clientes/$clienteId/analisis-ia'
    | '/app/clientes/$clienteId/coaching'
    | '/app/clientes/$clienteId/contactos'
    | '/app/clientes/$clienteId/cotizaciones'
    | '/app/clientes/$clienteId/empresa'
    | '/app/clientes/$clienteId/lee'
    | '/app/clientes/$clienteId/onboarding'
    | '/app/clientes/$clienteId/plan'
    | '/app/clientes/$clienteId/resumen'
    | '/app/clientes/$clienteId/side'
    | '/app/clientes/$clienteId/lee/$capitulo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/admin-simple'
    | '/app/clientes'
    | '/app/configuracion'
    | '/app/crecimiento'
    | '/app/dashboard'
    | '/app/evaluacion-competencias'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/share/$token'
    | '/app/clientes/$clienteId'
    | '/app/coaching/metodologia'
    | '/app/coaching/resultados'
    | '/app/manual-funciones/$clienteId'
    | '/app/side/historial'
    | '/app/coaching'
    | '/app/manual-funciones'
    | '/app/clientes/$clienteId/actividades'
    | '/app/clientes/$clienteId/analisis-ia'
    | '/app/clientes/$clienteId/coaching'
    | '/app/clientes/$clienteId/contactos'
    | '/app/clientes/$clienteId/cotizaciones'
    | '/app/clientes/$clienteId/empresa'
    | '/app/clientes/$clienteId/lee'
    | '/app/clientes/$clienteId/onboarding'
    | '/app/clientes/$clienteId/plan'
    | '/app/clientes/$clienteId/resumen'
    | '/app/clientes/$clienteId/side'
    | '/app/clientes/$clienteId/lee/$capitulo'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/admin-simple'
    | '/app/clientes'
    | '/app/configuracion'
    | '/app/crecimiento'
    | '/app/dashboard'
    | '/app/evaluacion-competencias'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/share/$token'
    | '/app/clientes/$clienteId'
    | '/app/coaching/metodologia'
    | '/app/coaching/resultados'
    | '/app/manual-funciones/$clienteId'
    | '/app/side_/historial'
    | '/app/coaching/'
    | '/app/manual-funciones/'
    | '/app/clientes/$clienteId/actividades'
    | '/app/clientes/$clienteId/analisis-ia'
    | '/app/clientes/$clienteId/coaching'
    | '/app/clientes/$clienteId/contactos'
    | '/app/clientes/$clienteId/cotizaciones'
    | '/app/clientes/$clienteId/empresa'
    | '/app/clientes/$clienteId/lee'
    | '/app/clientes/$clienteId/onboarding'
    | '/app/clientes/$clienteId/plan'
    | '/app/clientes/$clienteId/resumen'
    | '/app/clientes/$clienteId/side'
    | '/app/clientes/$clienteId/lee/$capitulo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/side': {
      id: '/app/side'
      path: '/side'
      fullPath: '/app/side'
      preLoaderRoute: typeof AppSideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lee': {
      id: '/app/lee'
      path: '/lee'
      fullPath: '/app/lee'
      preLoaderRoute: typeof AppLeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kpis': {
      id: '/app/kpis'
      path: '/kpis'
      fullPath: '/app/kpis'
      preLoaderRoute: typeof AppKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evaluacion-competencias': {
      id: '/app/evaluacion-competencias'
      path: '/evaluacion-competencias'
      fullPath: '/app/evaluacion-competencias'
      preLoaderRoute: typeof AppEvaluacionCompetenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crecimiento': {
      id: '/app/crecimiento'
      path: '/crecimiento'
      fullPath: '/app/crecimiento'
      preLoaderRoute: typeof AppCrecimientoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin-simple': {
      id: '/app/admin-simple'
      path: '/admin-simple'
      fullPath: '/app/admin-simple'
      preLoaderRoute: typeof AppAdminSimpleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manual-funciones/': {
      id: '/app/manual-funciones/'
      path: '/manual-funciones'
      fullPath: '/app/manual-funciones/'
      preLoaderRoute: typeof AppManualFuncionesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaching/': {
      id: '/app/coaching/'
      path: '/coaching'
      fullPath: '/app/coaching/'
      preLoaderRoute: typeof AppCoachingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/side_/historial': {
      id: '/app/side_/historial'
      path: '/side/historial'
      fullPath: '/app/side/historial'
      preLoaderRoute: typeof AppSideHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manual-funciones/$clienteId': {
      id: '/app/manual-funciones/$clienteId'
      path: '/manual-funciones/$clienteId'
      fullPath: '/app/manual-funciones/$clienteId'
      preLoaderRoute: typeof AppManualFuncionesClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaching/resultados': {
      id: '/app/coaching/resultados'
      path: '/coaching/resultados'
      fullPath: '/app/coaching/resultados'
      preLoaderRoute: typeof AppCoachingResultadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaching/metodologia': {
      id: '/app/coaching/metodologia'
      path: '/coaching/metodologia'
      fullPath: '/app/coaching/metodologia'
      preLoaderRoute: typeof AppCoachingMetodologiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$clienteId': {
      id: '/app/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/app/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/clientes/$clienteId/side': {
      id: '/app/clientes/$clienteId/side'
      path: '/side'
      fullPath: '/app/clientes/$clienteId/side'
      preLoaderRoute: typeof AppClientesClienteIdSideRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/resumen': {
      id: '/app/clientes/$clienteId/resumen'
      path: '/resumen'
      fullPath: '/app/clientes/$clienteId/resumen'
      preLoaderRoute: typeof AppClientesClienteIdResumenRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/plan': {
      id: '/app/clientes/$clienteId/plan'
      path: '/plan'
      fullPath: '/app/clientes/$clienteId/plan'
      preLoaderRoute: typeof AppClientesClienteIdPlanRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/onboarding': {
      id: '/app/clientes/$clienteId/onboarding'
      path: '/onboarding'
      fullPath: '/app/clientes/$clienteId/onboarding'
      preLoaderRoute: typeof AppClientesClienteIdOnboardingRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/lee': {
      id: '/app/clientes/$clienteId/lee'
      path: '/lee'
      fullPath: '/app/clientes/$clienteId/lee'
      preLoaderRoute: typeof AppClientesClienteIdLeeRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/empresa': {
      id: '/app/clientes/$clienteId/empresa'
      path: '/empresa'
      fullPath: '/app/clientes/$clienteId/empresa'
      preLoaderRoute: typeof AppClientesClienteIdEmpresaRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/cotizaciones': {
      id: '/app/clientes/$clienteId/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/app/clientes/$clienteId/cotizaciones'
      preLoaderRoute: typeof AppClientesClienteIdCotizacionesRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/contactos': {
      id: '/app/clientes/$clienteId/contactos'
      path: '/contactos'
      fullPath: '/app/clientes/$clienteId/contactos'
      preLoaderRoute: typeof AppClientesClienteIdContactosRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/coaching': {
      id: '/app/clientes/$clienteId/coaching'
      path: '/coaching'
      fullPath: '/app/clientes/$clienteId/coaching'
      preLoaderRoute: typeof AppClientesClienteIdCoachingRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/analisis-ia': {
      id: '/app/clientes/$clienteId/analisis-ia'
      path: '/analisis-ia'
      fullPath: '/app/clientes/$clienteId/analisis-ia'
      preLoaderRoute: typeof AppClientesClienteIdAnalisisIaRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/actividades': {
      id: '/app/clientes/$clienteId/actividades'
      path: '/actividades'
      fullPath: '/app/clientes/$clienteId/actividades'
      preLoaderRoute: typeof AppClientesClienteIdActividadesRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/lee/$capitulo': {
      id: '/app/clientes/$clienteId/lee/$capitulo'
      path: '/$capitulo'
      fullPath: '/app/clientes/$clienteId/lee/$capitulo'
      preLoaderRoute: typeof AppClientesClienteIdLeeCapituloRouteImport
      parentRoute: typeof AppClientesClienteIdLeeRoute
    }
  }
}

interface AppClientesClienteIdLeeRouteChildren {
  AppClientesClienteIdLeeCapituloRoute: typeof AppClientesClienteIdLeeCapituloRoute
}

const AppClientesClienteIdLeeRouteChildren: AppClientesClienteIdLeeRouteChildren =
  {
    AppClientesClienteIdLeeCapituloRoute: AppClientesClienteIdLeeCapituloRoute,
  }

const AppClientesClienteIdLeeRouteWithChildren =
  AppClientesClienteIdLeeRoute._addFileChildren(
    AppClientesClienteIdLeeRouteChildren,
  )

interface AppClientesClienteIdRouteChildren {
  AppClientesClienteIdActividadesRoute: typeof AppClientesClienteIdActividadesRoute
  AppClientesClienteIdAnalisisIaRoute: typeof AppClientesClienteIdAnalisisIaRoute
  AppClientesClienteIdCoachingRoute: typeof AppClientesClienteIdCoachingRoute
  AppClientesClienteIdContactosRoute: typeof AppClientesClienteIdContactosRoute
  AppClientesClienteIdCotizacionesRoute: typeof AppClientesClienteIdCotizacionesRoute
  AppClientesClienteIdEmpresaRoute: typeof AppClientesClienteIdEmpresaRoute
  AppClientesClienteIdLeeRoute: typeof AppClientesClienteIdLeeRouteWithChildren
  AppClientesClienteIdOnboardingRoute: typeof AppClientesClienteIdOnboardingRoute
  AppClientesClienteIdPlanRoute: typeof AppClientesClienteIdPlanRoute
  AppClientesClienteIdResumenRoute: typeof AppClientesClienteIdResumenRoute
  AppClientesClienteIdSideRoute: typeof AppClientesClienteIdSideRoute
}

const AppClientesClienteIdRouteChildren: AppClientesClienteIdRouteChildren = {
  AppClientesClienteIdActividadesRoute: AppClientesClienteIdActividadesRoute,
  AppClientesClienteIdAnalisisIaRoute: AppClientesClienteIdAnalisisIaRoute,
  AppClientesClienteIdCoachingRoute: AppClientesClienteIdCoachingRoute,
  AppClientesClienteIdContactosRoute: AppClientesClienteIdContactosRoute,
  AppClientesClienteIdCotizacionesRoute: AppClientesClienteIdCotizacionesRoute,
  AppClientesClienteIdEmpresaRoute: AppClientesClienteIdEmpresaRoute,
  AppClientesClienteIdLeeRoute: AppClientesClienteIdLeeRouteWithChildren,
  AppClientesClienteIdOnboardingRoute: AppClientesClienteIdOnboardingRoute,
  AppClientesClienteIdPlanRoute: AppClientesClienteIdPlanRoute,
  AppClientesClienteIdResumenRoute: AppClientesClienteIdResumenRoute,
  AppClientesClienteIdSideRoute: AppClientesClienteIdSideRoute,
}

const AppClientesClienteIdRouteWithChildren =
  AppClientesClienteIdRoute._addFileChildren(AppClientesClienteIdRouteChildren)

interface AppClientesRouteChildren {
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRouteWithChildren
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesClienteIdRoute: AppClientesClienteIdRouteWithChildren,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppAdminSimpleRoute: typeof AppAdminSimpleRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppCrecimientoRoute: typeof AppCrecimientoRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEvaluacionCompetenciasRoute: typeof AppEvaluacionCompetenciasRoute
  AppKpisRoute: typeof AppKpisRoute
  AppLeeRoute: typeof AppLeeRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSideRoute: typeof AppSideRoute
  AppCoachingMetodologiaRoute: typeof AppCoachingMetodologiaRoute
  AppCoachingResultadosRoute: typeof AppCoachingResultadosRoute
  AppManualFuncionesClienteIdRoute: typeof AppManualFuncionesClienteIdRoute
  AppSideHistorialRoute: typeof AppSideHistorialRoute
  AppCoachingIndexRoute: typeof AppCoachingIndexRoute
  AppManualFuncionesIndexRoute: typeof AppManualFuncionesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminSimpleRoute: AppAdminSimpleRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppCrecimientoRoute: AppCrecimientoRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEvaluacionCompetenciasRoute: AppEvaluacionCompetenciasRoute,
  AppKpisRoute: AppKpisRoute,
  AppLeeRoute: AppLeeRoute,
  AppPlanRoute: AppPlanRoute,
  AppSideRoute: AppSideRoute,
  AppCoachingMetodologiaRoute: AppCoachingMetodologiaRoute,
  AppCoachingResultadosRoute: AppCoachingResultadosRoute,
  AppManualFuncionesClienteIdRoute: AppManualFuncionesClienteIdRoute,
  AppSideHistorialRoute: AppSideHistorialRoute,
  AppCoachingIndexRoute: AppCoachingIndexRoute,
  AppManualFuncionesIndexRoute: AppManualFuncionesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
