/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSideRouteImport } from './routes/app.side'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppLeeRouteImport } from './routes/app.lee'
import { Route as AppKpisRouteImport } from './routes/app.kpis'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConfiguracionRouteImport } from './routes/app.configuracion'
import { Route as AppCoachingRouteImport } from './routes/app.coaching'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppSideHistorialRouteImport } from './routes/app.side_.historial'
import { Route as AppClientesClienteIdRouteImport } from './routes/app.clientes.$clienteId'
import { Route as AppClientesClienteIdSideRouteImport } from './routes/app.clientes.$clienteId.side'
import { Route as AppClientesClienteIdResumenRouteImport } from './routes/app.clientes.$clienteId.resumen'
import { Route as AppClientesClienteIdPlanRouteImport } from './routes/app.clientes.$clienteId.plan'
import { Route as AppClientesClienteIdOnboardingRouteImport } from './routes/app.clientes.$clienteId.onboarding'
import { Route as AppClientesClienteIdLeeRouteImport } from './routes/app.clientes.$clienteId.lee'
import { Route as AppClientesClienteIdEmpresaRouteImport } from './routes/app.clientes.$clienteId.empresa'
import { Route as AppClientesClienteIdCotizacionesRouteImport } from './routes/app.clientes.$clienteId.cotizaciones'
import { Route as AppClientesClienteIdContactosRouteImport } from './routes/app.clientes.$clienteId.contactos'
import { Route as AppClientesClienteIdCoachingRouteImport } from './routes/app.clientes.$clienteId.coaching'
import { Route as AppClientesClienteIdAnalisisIaRouteImport } from './routes/app.clientes.$clienteId.analisis-ia'
import { Route as AppClientesClienteIdActividadesRouteImport } from './routes/app.clientes.$clienteId.actividades'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSideRoute = AppSideRouteImport.update({
  id: '/side',
  path: '/side',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppLeeRoute = AppLeeRouteImport.update({
  id: '/lee',
  path: '/lee',
  getParentRoute: () => AppRoute,
} as any)
const AppKpisRoute = AppKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingRoute = AppCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppSideHistorialRoute = AppSideHistorialRouteImport.update({
  id: '/side_/historial',
  path: '/side/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesClienteIdSideRoute =
  AppClientesClienteIdSideRouteImport.update({
    id: '/side',
    path: '/side',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdResumenRoute =
  AppClientesClienteIdResumenRouteImport.update({
    id: '/resumen',
    path: '/resumen',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdPlanRoute =
  AppClientesClienteIdPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdOnboardingRoute =
  AppClientesClienteIdOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdLeeRoute = AppClientesClienteIdLeeRouteImport.update({
  id: '/lee',
  path: '/lee',
  getParentRoute: () => AppClientesClienteIdRoute,
} as any)
const AppClientesClienteIdEmpresaRoute =
  AppClientesClienteIdEmpresaRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdCotizacionesRoute =
  AppClientesClienteIdCotizacionesRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdContactosRoute =
  AppClientesClienteIdContactosRouteImport.update({
    id: '/contactos',
    path: '/contactos',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdCoachingRoute =
  AppClientesClienteIdCoachingRouteImport.update({
    id: '/coaching',
    path: '/coaching',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdAnalisisIaRoute =
  AppClientesClienteIdAnalisisIaRouteImport.update({
    id: '/analisis-ia',
    path: '/analisis-ia',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)
const AppClientesClienteIdActividadesRoute =
  AppClientesClienteIdActividadesRouteImport.update({
    id: '/actividades',
    path: '/actividades',
    getParentRoute: () => AppClientesClienteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/coaching': typeof AppCoachingRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRouteWithChildren
  '/app/side/historial': typeof AppSideHistorialRoute
  '/app/clientes/$clienteId/actividades': typeof AppClientesClienteIdActividadesRoute
  '/app/clientes/$clienteId/analisis-ia': typeof AppClientesClienteIdAnalisisIaRoute
  '/app/clientes/$clienteId/coaching': typeof AppClientesClienteIdCoachingRoute
  '/app/clientes/$clienteId/contactos': typeof AppClientesClienteIdContactosRoute
  '/app/clientes/$clienteId/cotizaciones': typeof AppClientesClienteIdCotizacionesRoute
  '/app/clientes/$clienteId/empresa': typeof AppClientesClienteIdEmpresaRoute
  '/app/clientes/$clienteId/lee': typeof AppClientesClienteIdLeeRoute
  '/app/clientes/$clienteId/onboarding': typeof AppClientesClienteIdOnboardingRoute
  '/app/clientes/$clienteId/plan': typeof AppClientesClienteIdPlanRoute
  '/app/clientes/$clienteId/resumen': typeof AppClientesClienteIdResumenRoute
  '/app/clientes/$clienteId/side': typeof AppClientesClienteIdSideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/coaching': typeof AppCoachingRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRouteWithChildren
  '/app/side/historial': typeof AppSideHistorialRoute
  '/app/clientes/$clienteId/actividades': typeof AppClientesClienteIdActividadesRoute
  '/app/clientes/$clienteId/analisis-ia': typeof AppClientesClienteIdAnalisisIaRoute
  '/app/clientes/$clienteId/coaching': typeof AppClientesClienteIdCoachingRoute
  '/app/clientes/$clienteId/contactos': typeof AppClientesClienteIdContactosRoute
  '/app/clientes/$clienteId/cotizaciones': typeof AppClientesClienteIdCotizacionesRoute
  '/app/clientes/$clienteId/empresa': typeof AppClientesClienteIdEmpresaRoute
  '/app/clientes/$clienteId/lee': typeof AppClientesClienteIdLeeRoute
  '/app/clientes/$clienteId/onboarding': typeof AppClientesClienteIdOnboardingRoute
  '/app/clientes/$clienteId/plan': typeof AppClientesClienteIdPlanRoute
  '/app/clientes/$clienteId/resumen': typeof AppClientesClienteIdResumenRoute
  '/app/clientes/$clienteId/side': typeof AppClientesClienteIdSideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/coaching': typeof AppCoachingRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRouteWithChildren
  '/app/side_/historial': typeof AppSideHistorialRoute
  '/app/clientes/$clienteId/actividades': typeof AppClientesClienteIdActividadesRoute
  '/app/clientes/$clienteId/analisis-ia': typeof AppClientesClienteIdAnalisisIaRoute
  '/app/clientes/$clienteId/coaching': typeof AppClientesClienteIdCoachingRoute
  '/app/clientes/$clienteId/contactos': typeof AppClientesClienteIdContactosRoute
  '/app/clientes/$clienteId/cotizaciones': typeof AppClientesClienteIdCotizacionesRoute
  '/app/clientes/$clienteId/empresa': typeof AppClientesClienteIdEmpresaRoute
  '/app/clientes/$clienteId/lee': typeof AppClientesClienteIdLeeRoute
  '/app/clientes/$clienteId/onboarding': typeof AppClientesClienteIdOnboardingRoute
  '/app/clientes/$clienteId/plan': typeof AppClientesClienteIdPlanRoute
  '/app/clientes/$clienteId/resumen': typeof AppClientesClienteIdResumenRoute
  '/app/clientes/$clienteId/side': typeof AppClientesClienteIdSideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/clientes'
    | '/app/coaching'
    | '/app/configuracion'
    | '/app/dashboard'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/app/clientes/$clienteId'
    | '/app/side/historial'
    | '/app/clientes/$clienteId/actividades'
    | '/app/clientes/$clienteId/analisis-ia'
    | '/app/clientes/$clienteId/coaching'
    | '/app/clientes/$clienteId/contactos'
    | '/app/clientes/$clienteId/cotizaciones'
    | '/app/clientes/$clienteId/empresa'
    | '/app/clientes/$clienteId/lee'
    | '/app/clientes/$clienteId/onboarding'
    | '/app/clientes/$clienteId/plan'
    | '/app/clientes/$clienteId/resumen'
    | '/app/clientes/$clienteId/side'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/clientes'
    | '/app/coaching'
    | '/app/configuracion'
    | '/app/dashboard'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/app/clientes/$clienteId'
    | '/app/side/historial'
    | '/app/clientes/$clienteId/actividades'
    | '/app/clientes/$clienteId/analisis-ia'
    | '/app/clientes/$clienteId/coaching'
    | '/app/clientes/$clienteId/contactos'
    | '/app/clientes/$clienteId/cotizaciones'
    | '/app/clientes/$clienteId/empresa'
    | '/app/clientes/$clienteId/lee'
    | '/app/clientes/$clienteId/onboarding'
    | '/app/clientes/$clienteId/plan'
    | '/app/clientes/$clienteId/resumen'
    | '/app/clientes/$clienteId/side'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/clientes'
    | '/app/coaching'
    | '/app/configuracion'
    | '/app/dashboard'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/app/clientes/$clienteId'
    | '/app/side_/historial'
    | '/app/clientes/$clienteId/actividades'
    | '/app/clientes/$clienteId/analisis-ia'
    | '/app/clientes/$clienteId/coaching'
    | '/app/clientes/$clienteId/contactos'
    | '/app/clientes/$clienteId/cotizaciones'
    | '/app/clientes/$clienteId/empresa'
    | '/app/clientes/$clienteId/lee'
    | '/app/clientes/$clienteId/onboarding'
    | '/app/clientes/$clienteId/plan'
    | '/app/clientes/$clienteId/resumen'
    | '/app/clientes/$clienteId/side'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/side': {
      id: '/app/side'
      path: '/side'
      fullPath: '/app/side'
      preLoaderRoute: typeof AppSideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lee': {
      id: '/app/lee'
      path: '/lee'
      fullPath: '/app/lee'
      preLoaderRoute: typeof AppLeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kpis': {
      id: '/app/kpis'
      path: '/kpis'
      fullPath: '/app/kpis'
      preLoaderRoute: typeof AppKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaching': {
      id: '/app/coaching'
      path: '/coaching'
      fullPath: '/app/coaching'
      preLoaderRoute: typeof AppCoachingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/side_/historial': {
      id: '/app/side_/historial'
      path: '/side/historial'
      fullPath: '/app/side/historial'
      preLoaderRoute: typeof AppSideHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$clienteId': {
      id: '/app/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/app/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/clientes/$clienteId/side': {
      id: '/app/clientes/$clienteId/side'
      path: '/side'
      fullPath: '/app/clientes/$clienteId/side'
      preLoaderRoute: typeof AppClientesClienteIdSideRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/resumen': {
      id: '/app/clientes/$clienteId/resumen'
      path: '/resumen'
      fullPath: '/app/clientes/$clienteId/resumen'
      preLoaderRoute: typeof AppClientesClienteIdResumenRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/plan': {
      id: '/app/clientes/$clienteId/plan'
      path: '/plan'
      fullPath: '/app/clientes/$clienteId/plan'
      preLoaderRoute: typeof AppClientesClienteIdPlanRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/onboarding': {
      id: '/app/clientes/$clienteId/onboarding'
      path: '/onboarding'
      fullPath: '/app/clientes/$clienteId/onboarding'
      preLoaderRoute: typeof AppClientesClienteIdOnboardingRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/lee': {
      id: '/app/clientes/$clienteId/lee'
      path: '/lee'
      fullPath: '/app/clientes/$clienteId/lee'
      preLoaderRoute: typeof AppClientesClienteIdLeeRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/empresa': {
      id: '/app/clientes/$clienteId/empresa'
      path: '/empresa'
      fullPath: '/app/clientes/$clienteId/empresa'
      preLoaderRoute: typeof AppClientesClienteIdEmpresaRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/cotizaciones': {
      id: '/app/clientes/$clienteId/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/app/clientes/$clienteId/cotizaciones'
      preLoaderRoute: typeof AppClientesClienteIdCotizacionesRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/contactos': {
      id: '/app/clientes/$clienteId/contactos'
      path: '/contactos'
      fullPath: '/app/clientes/$clienteId/contactos'
      preLoaderRoute: typeof AppClientesClienteIdContactosRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/coaching': {
      id: '/app/clientes/$clienteId/coaching'
      path: '/coaching'
      fullPath: '/app/clientes/$clienteId/coaching'
      preLoaderRoute: typeof AppClientesClienteIdCoachingRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/analisis-ia': {
      id: '/app/clientes/$clienteId/analisis-ia'
      path: '/analisis-ia'
      fullPath: '/app/clientes/$clienteId/analisis-ia'
      preLoaderRoute: typeof AppClientesClienteIdAnalisisIaRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
    '/app/clientes/$clienteId/actividades': {
      id: '/app/clientes/$clienteId/actividades'
      path: '/actividades'
      fullPath: '/app/clientes/$clienteId/actividades'
      preLoaderRoute: typeof AppClientesClienteIdActividadesRouteImport
      parentRoute: typeof AppClientesClienteIdRoute
    }
  }
}

interface AppClientesClienteIdRouteChildren {
  AppClientesClienteIdActividadesRoute: typeof AppClientesClienteIdActividadesRoute
  AppClientesClienteIdAnalisisIaRoute: typeof AppClientesClienteIdAnalisisIaRoute
  AppClientesClienteIdCoachingRoute: typeof AppClientesClienteIdCoachingRoute
  AppClientesClienteIdContactosRoute: typeof AppClientesClienteIdContactosRoute
  AppClientesClienteIdCotizacionesRoute: typeof AppClientesClienteIdCotizacionesRoute
  AppClientesClienteIdEmpresaRoute: typeof AppClientesClienteIdEmpresaRoute
  AppClientesClienteIdLeeRoute: typeof AppClientesClienteIdLeeRoute
  AppClientesClienteIdOnboardingRoute: typeof AppClientesClienteIdOnboardingRoute
  AppClientesClienteIdPlanRoute: typeof AppClientesClienteIdPlanRoute
  AppClientesClienteIdResumenRoute: typeof AppClientesClienteIdResumenRoute
  AppClientesClienteIdSideRoute: typeof AppClientesClienteIdSideRoute
}

const AppClientesClienteIdRouteChildren: AppClientesClienteIdRouteChildren = {
  AppClientesClienteIdActividadesRoute: AppClientesClienteIdActividadesRoute,
  AppClientesClienteIdAnalisisIaRoute: AppClientesClienteIdAnalisisIaRoute,
  AppClientesClienteIdCoachingRoute: AppClientesClienteIdCoachingRoute,
  AppClientesClienteIdContactosRoute: AppClientesClienteIdContactosRoute,
  AppClientesClienteIdCotizacionesRoute: AppClientesClienteIdCotizacionesRoute,
  AppClientesClienteIdEmpresaRoute: AppClientesClienteIdEmpresaRoute,
  AppClientesClienteIdLeeRoute: AppClientesClienteIdLeeRoute,
  AppClientesClienteIdOnboardingRoute: AppClientesClienteIdOnboardingRoute,
  AppClientesClienteIdPlanRoute: AppClientesClienteIdPlanRoute,
  AppClientesClienteIdResumenRoute: AppClientesClienteIdResumenRoute,
  AppClientesClienteIdSideRoute: AppClientesClienteIdSideRoute,
}

const AppClientesClienteIdRouteWithChildren =
  AppClientesClienteIdRoute._addFileChildren(AppClientesClienteIdRouteChildren)

interface AppClientesRouteChildren {
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRouteWithChildren
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesClienteIdRoute: AppClientesClienteIdRouteWithChildren,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppCoachingRoute: typeof AppCoachingRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKpisRoute: typeof AppKpisRoute
  AppLeeRoute: typeof AppLeeRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSideRoute: typeof AppSideRoute
  AppSideHistorialRoute: typeof AppSideHistorialRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRouteWithChildren,
  AppCoachingRoute: AppCoachingRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKpisRoute: AppKpisRoute,
  AppLeeRoute: AppLeeRoute,
  AppPlanRoute: AppPlanRoute,
  AppSideRoute: AppSideRoute,
  AppSideHistorialRoute: AppSideHistorialRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
