/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSideRouteImport } from './routes/app.side'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppLeeRouteImport } from './routes/app.lee'
import { Route as AppKpisRouteImport } from './routes/app.kpis'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConfiguracionRouteImport } from './routes/app.configuracion'
import { Route as AppCoachingRouteImport } from './routes/app.coaching'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppSideHistorialRouteImport } from './routes/app.side_.historial'
import { Route as AppClientesClienteIdRouteImport } from './routes/app.clientes.$clienteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSideRoute = AppSideRouteImport.update({
  id: '/side',
  path: '/side',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppLeeRoute = AppLeeRouteImport.update({
  id: '/lee',
  path: '/lee',
  getParentRoute: () => AppRoute,
} as any)
const AppKpisRoute = AppKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingRoute = AppCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppSideHistorialRoute = AppSideHistorialRouteImport.update({
  id: '/side_/historial',
  path: '/side/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/coaching': typeof AppCoachingRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/side/historial': typeof AppSideHistorialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/coaching': typeof AppCoachingRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/side/historial': typeof AppSideHistorialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/coaching': typeof AppCoachingRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/lee': typeof AppLeeRoute
  '/app/plan': typeof AppPlanRoute
  '/app/side': typeof AppSideRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/side_/historial': typeof AppSideHistorialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/clientes'
    | '/app/coaching'
    | '/app/configuracion'
    | '/app/dashboard'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/app/clientes/$clienteId'
    | '/app/side/historial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/clientes'
    | '/app/coaching'
    | '/app/configuracion'
    | '/app/dashboard'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/app/clientes/$clienteId'
    | '/app/side/historial'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/clientes'
    | '/app/coaching'
    | '/app/configuracion'
    | '/app/dashboard'
    | '/app/kpis'
    | '/app/lee'
    | '/app/plan'
    | '/app/side'
    | '/app/clientes/$clienteId'
    | '/app/side_/historial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/side': {
      id: '/app/side'
      path: '/side'
      fullPath: '/app/side'
      preLoaderRoute: typeof AppSideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lee': {
      id: '/app/lee'
      path: '/lee'
      fullPath: '/app/lee'
      preLoaderRoute: typeof AppLeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kpis': {
      id: '/app/kpis'
      path: '/kpis'
      fullPath: '/app/kpis'
      preLoaderRoute: typeof AppKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaching': {
      id: '/app/coaching'
      path: '/coaching'
      fullPath: '/app/coaching'
      preLoaderRoute: typeof AppCoachingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/side_/historial': {
      id: '/app/side_/historial'
      path: '/side/historial'
      fullPath: '/app/side/historial'
      preLoaderRoute: typeof AppSideHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$clienteId': {
      id: '/app/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/app/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesClienteIdRoute: AppClientesClienteIdRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppCoachingRoute: typeof AppCoachingRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKpisRoute: typeof AppKpisRoute
  AppLeeRoute: typeof AppLeeRoute
  AppPlanRoute: typeof AppPlanRoute
  AppSideRoute: typeof AppSideRoute
  AppSideHistorialRoute: typeof AppSideHistorialRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRouteWithChildren,
  AppCoachingRoute: AppCoachingRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKpisRoute: AppKpisRoute,
  AppLeeRoute: AppLeeRoute,
  AppPlanRoute: AppPlanRoute,
  AppSideRoute: AppSideRoute,
  AppSideHistorialRoute: AppSideHistorialRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
